## Prepare all manifests locally
- hosts: localhost
  tasks:
  - include_role:
      name: arangodb-operator
    tags: operator


## Upload manifests to the K8S cluster via ssh to the master node
- hosts: master
  vars:
    kubernetes_manifests: "{{ hostvars['localhost']['_kustomize']['stdout'] }}"
  tasks:
  - block:
    - include_vars:
        dir: arangodb-operator/defaults
    - include_tasks: arangodb-operator/tasks/k8s.yml
    tags: operator
